/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ventExTyscvZpogFdoiw6H
// Component: 8Pj7c1BH86
import * as React from "react";
import {
  hasVariant,
  createPlasmicElement,
  RenderOpts,
  Override,
  classNames,
  Flex,
  RenderFunc,
  RenderFuncOverrides,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg
} from "@plasmicapp/react-web";
import Link from "../../Link"; // plasmic-import: yIoAz1MvEm/component
import { PlasmicLink__VariantsArgs } from "./PlasmicLink"; // plasmic-import: yIoAz1MvEm/render

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "../untitled_project/plasmic_untitled_project.css"; // plasmic-import: ventExTyscvZpogFdoiw6H/projectcss
import "./PlasmicStreamlineIconsLink.css"; // plasmic-import: 8Pj7c1BH86/css

export type PlasmicStreamlineIconsLink__VariantsArgs = {};

export type PlasmicStreamlineIconsLink__GlobalVariantsType = {};

export type PlasmicStreamlineIconsLink__ArgsType = {};

export type PlasmicStreamlineIconsLink__TriggerStateType = {};

export class PlasmicStreamlineIconsLink__RenderHelper {
  constructor(
    readonly variants: PlasmicStreamlineIconsLink__VariantsArgs,
    readonly args: PlasmicStreamlineIconsLink__ArgsType,
    readonly rootClassName: string | undefined
  ) {}

  private rawProps2 = () => {
    const args = this.args;
    const variants = this.variants;

    return {};
  };

  props2 = (
    modifier?: (
      props: ReturnType<PlasmicStreamlineIconsLink__RenderHelper["rawProps2"]>
    ) => void
  ) => {
    // [Ds-eg8EqW, 2]: Don't modify this line
    const props = this.rawProps2();
    if (modifier) {
      modifier(props);
    }
    return props;
  };
  cls2 = () => {
    // [Ds-eg8EqW, 2]: Don't modify this line

    const args = this.args;
    const variants = this.variants;

    return classNames({
      "StreamlineIconsLink___2__Ds-eg": true,
      "plasmic-default__all": true,
      "plasmic-default__div": true
    });
  };
  cls4 = () => {
    // [_2KujUrRo5, 4]: Don't modify this line

    const args = this.args;
    const variants = this.variants;

    return classNames({
      StreamlineIconsLink___4___2Kuj: true,
      __wab_instance: true
    });
  };

  private rawProps4 = () => {
    const args = this.args;
    const variants = this.variants;

    return {
      className: classNames({
        StreamlineIconsLink___4___2Kuj: true,
        __wab_instance: true
      })
    };
  };

  props4 = (
    modifier?: (
      props: ReturnType<PlasmicStreamlineIconsLink__RenderHelper["rawProps4"]>
    ) => void
  ) => {
    // [_2KujUrRo5, 4]: Don't modify this line
    const props = this.rawProps4();
    if (modifier) {
      modifier(props);
    }
    return props;
  };

  private rawProps1 = () => {
    const args = this.args;
    const variants = this.variants;

    return {};
  };

  props1 = (
    modifier?: (
      props: ReturnType<PlasmicStreamlineIconsLink__RenderHelper["rawProps1"]>
    ) => void
  ) => {
    // [bP8NHhK5O, 1]: Don't modify this line
    const props = this.rawProps1();
    if (modifier) {
      modifier(props);
    }
    return props;
  };
  cls1 = () => {
    // [bP8NHhK5O, 1]: Don't modify this line

    const args = this.args;
    const variants = this.variants;

    return (
      classNames({
        StreamlineIconsLink___1__bP8NH: true,
        "plasmic-default__all": true,
        "plasmic-default__div": true
      }) +
      " " +
      (this.rootClassName || "")
    );
  };
}

/* plasmic-nameInIdToUuid/503
      [
        [
          "1",
          "bP8NHhK5O"
        ],
        [
          "2",
          "Ds-eg8EqW"
        ],
        [
          "4",
          "_2KujUrRo5"
        ],
        [
          "$pos4",
          "@_2KujUrRo5"
        ]
      ]
      */

/* plasmic-vanilla-jsx/503
         <div className={rh.cls1()}  ><div className={rh.cls2()}  >{"Icon by "}</div>
         <Link {...rh.props4()}  className={rh.cls4()}/></div>
         */
/* prettier-ignore-end */
